[package]
name = "cpazk"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = "0.3.0"
zkhash = { git = "https://github.com/KryptonZK/zkfriendlyhashzoo-forked.git" }
rand = "0.8"
serde = { version = "1.0.202", features = ["serde_derive"] }
halo2_gadgets = "0.3.0"
group = "0.13.0"
